//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication12.Models
{
    using System;
    using WebApplication12.helper;

    using System.Collections.Generic;

    public partial class info
    {
        public int id { get; set; }
        public string name { get; set; }
        public string fname { get; set; }
        public string country { get; set; }

#region gender
        public int? gender { get; set; }


        public string Gendername
        {
            get

            {
                if (gender != null)
                {
                    if (gender == (int?)Gender.male)
                    {
                        return "male";

                    }
                    else if (gender == (int?)Gender.female)
                    {
                        return "female";
                    }
                    else
                    {
                        return "others";
                    }


                }
                else
                {
                    return "notselcted";
                }

            }

        }
#endregion

        public Nullable<System.DateTime> Datetime { get; set; }
    }
}